# Generated by Django 5.2.4 on 2025-07-07 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50, unique=True, verbose_name='Зав. № машины')),
                ('engine_serial', models.CharField(max_length=50, verbose_name='Зав. № двигателя')),
                ('transmission_serial', models.CharField(max_length=50, verbose_name='Зав. № трансмиссии')),
                ('drive_axle_serial', models.CharField(max_length=50, verbose_name='Зав. № ведущего моста')),
                ('steer_axle_serial', models.CharField(max_length=50, verbose_name='Зав. № управляемого моста')),
                ('supply_contract', models.CharField(max_length=100, verbose_name='Договор поставки №, дата')),
                ('shipment_date', models.DateField(verbose_name='Дата отгрузки с завода')),
                ('consignee', models.CharField(max_length=200, verbose_name='Грузополучатель (конечный потребитель)')),
                ('delivery_address', models.CharField(max_length=300, verbose_name='Адрес поставки (эксплуатации)')),
                ('equipment', models.TextField(blank=True, verbose_name='Комплектация (доп. опции)')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_machines', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('drive_axle_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directories.driveaxlemodel', verbose_name='Модель ведущего моста')),
                ('engine_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directories.enginemodel', verbose_name='Модель двигателя')),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directories.servicecompany', verbose_name='Сервисная компания')),
                ('steer_axle_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directories.steeraxlemodel', verbose_name='Модель управляемого моста')),
                ('technique_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directories.techniquemodel', verbose_name='Модель техники')),
                ('transmission_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directories.transmissionmodel', verbose_name='Модель трансмиссии')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
                'ordering': ['-shipment_date'],
            },
        ),
    ]
