# Generated by Django 5.2.4 on 2025-07-09 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0002_directory'),
        ('machines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_machines', to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='consignee',
            field=models.CharField(blank=True, max_length=200, verbose_name='Грузополучатель'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='delivery_address',
            field=models.TextField(blank=True, verbose_name='Адрес поставки'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='drive_axle_serial',
            field=models.CharField(max_length=50, verbose_name='Заводской номер ведущего моста'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='engine_serial',
            field=models.CharField(max_length=50, verbose_name='Заводской номер двигателя'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='equipment',
            field=models.TextField(blank=True, verbose_name='Комплектация'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='serial_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Заводской номер машины'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='service_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='serviced_machines', to='directories.servicecompany', verbose_name='Сервисная компания'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='steer_axle_serial',
            field=models.CharField(max_length=50, verbose_name='Заводской номер управляемого моста'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='supply_contract',
            field=models.CharField(blank=True, max_length=200, verbose_name='Договор поставки'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='transmission_serial',
            field=models.CharField(max_length=50, verbose_name='Заводской номер трансмиссии'),
        ),
    ]
