# Generated by Django 5.2.4 on 2025-07-09 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0002_directory'),
        ('machines', '0002_alter_machine_client_alter_machine_consignee_and_more'),
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.machine', verbose_name='Машина'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='operating_hours',
            field=models.PositiveIntegerField(verbose_name='Наработка, м/час'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='service_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='directories.servicecompany', verbose_name='Сервисная компания'),
        ),
    ]
